[variables]
MISE_PYTHON_GITHUB_ATTESTATIONS = "false"
DJANGO_SETTINGS_MODULE = "mind_nest.settings_production"
EMAIL_HOST_USER = "mohammadataelbassa1@gmail.com"
EMAIL_HOST_PASSWORD = "znnxkbucpfemqcot"
