# Generated by Django 5.2.17 on 2026-08-27 12:31

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0002_uploadeddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='ai_documents/'),
        ),
    ]
